openapi: 3.0.0
info:
  title: Event API
  version: 1.0.0
  description: API endpoints for event operations

components:
  schemas:
    Event:
      type: object
      properties:
        _id:
          type: string
          example: "507f1f77bcf86cd799439011"
        title:
          type: string
          example: "sample title"
        startDate:
          type: string
          example: "sample startDate"
        endDate:
          type: string
          example: "sample endDate"
        createdAt:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"

    CreateEventRequest:
      type: object
      required:
        - title
        - startDate
        - endDate
      properties:
        title:
          type: string
          example: "sample title"
        startDate:
          type: string
          example: "sample startDate"
        endDate:
          type: string
          example: "sample endDate"

    UpdateEventRequest:
      type: object
      properties:
        title:
          type: string
          example: "updated title"
        startDate:
          type: string
          example: "updated startDate"
        endDate:
          type: string
          example: "updated endDate"

paths:
  /api/event:
    get:
      summary: Get all events
      description: Retrieve all events
      responses:
        '200':
          description: Events retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Events retrieved successfully"

    post:
      summary: Create a new event
      description: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventRequest'
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Event'
                  status:
                    type: integer
                    example: 201
                  message:
                    type: string
                    example: "Event created successfully"

  /api/event/{id}:
    get:
      summary: Get event by ID
      description: Retrieve a event by its ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the event to retrieve
      responses:
        '200':
          description: Event retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Event'
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Event retrieved successfully"
        '404':
          description: Event not found

    put:
      summary: Update event
      description: Update a event by its ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the event to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventRequest'
      responses:
        '200':
          description: Event updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Event'
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Event updated successfully"
        '404':
          description: Event not found

    delete:
      summary: Delete event
      description: Delete a event by its ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the event to delete
      responses:
        '200':
          description: Event deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    nullable: true
                    example: null
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Event deleted successfully"
        '404':
          description: Event not found
          content:
          application/json:
              schema:
              type: object
              properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'Validation error: id is required'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "Failed to retrieve event"
