openapi: 3.0.0
info:
  title: Novels API
  version: 1.0.0
  description: API endpoints for novels operations

components:
  schemas:
    Novels:
      type: object
      properties:
        _id:
          type: string
          example: '507f1f77bcf86cd799439011'
        email:
          type: string
          example: 'sample email'
        age:
          type: number
          example: 123
        isActive:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
          example: '2023-01-01T00:00:00Z'
        updatedAt:
          type: string
          format: date-time
          example: '2023-01-01T00:00:00Z'

    CreateNovelsRequest:
      type: object
      required:
        - email
        - age
        - isActive
      properties:
        email:
          type: string
          example: 'sample email'
        age:
          type: number
          example: 123
        isActive:
          type: boolean
          example: true

    UpdateNovelsRequest:
      type: object
      properties:
        email:
          type: string
          example: 'updated email'
        age:
          type: number
          example: 456
        isActive:
          type: boolean
          example: false

paths:
  /api/novels:
    get:
      summary: Get all novelss
      description: Retrieve all novelss
      responses:
        '200':
          description: Novelss retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Novels'
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 'Novelss retrieved successfully'

    post:
      summary: Create a new novels
      description: Create a new novels
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNovelsRequest'
      responses:
        '201':
          description: Novels created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Novels'
                  status:
                    type: integer
                    example: 201
                  message:
                    type: string
                    example: 'Novels created successfully'

  /api/novels/{id}:
    get:
      summary: Get novels by ID
      description: Retrieve a novels by its ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the novels to retrieve
      responses:
        '200':
          description: Novels retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Novels'
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 'Novels retrieved successfully'
        '404':
          description: Novels not found

    put:
      summary: Update novels
      description: Update a novels by its ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the novels to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateNovelsRequest'
      responses:
        '200':
          description: Novels updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Novels'
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 'Novels updated successfully'
        '404':
          description: Novels not found

    delete:
      summary: Delete novels
      description: Delete a novels by its ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the novels to delete
      responses:
        '200':
          description: Novels deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    nullable: true
                    example: null
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 'Novels deleted successfully'
        '404':
          description: Novels not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'Validation error: id is required'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: 'Failed to retrieve novels'
