openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API endpoints for user operations

paths:
  /api/user:
    get:
      summary: Get user by ID
      description: Retrieve a user by its ID
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
            minLength: 1
          description: The ID of the user to retrieve
      responses:
        '200':
          description: User retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "test-id-123"
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "User retrieved successfully"
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: "Validation error: id is required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 500
                  message:
                    type: string
                    example: "Failed to retrieve user"
